sudo: required
language: c
branches:
    except:
        - packaging
        - docsdevel

before_install:
    - sudo apt-get update

install:
    - sudo apt-get install gcc-avr binutils-avr avr-libc valgrind pastebinit cppcheck cmake
    - pip install --user cpp-coveralls

script:
    # Normal build
    - cd test
    - make all
    - ./test < test-requests.txt

    # Coverage test
    - make COVERAGE=1
    - ./test < test-requests.txt

after_success:
    - coveralls --verbose ../include/lightmodbus/base.impl.h ../include/lightmodbus/slave.impl.h ../include/lightmodbus/slave_func.impl.h
    # - find . -name "*.c" | xargs cppcheck > cppcheck.log
    # - TARBALL=$(date +liblightmodbus-travis-%Y-%m-%d--%H-%M-%S.tar)
    # - tar -cvf $TARBALL .
    # - curl -F file="@$TARBALL" https://filebin.ca/upload.php
