name: Basic test (v3.0)

on:
  push:
    branches: [ dev-v3.0 ]
  pull_request:
    branches: [ dev-v3.0 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build basic test
      run: make -C test/basic
    - name: Run basic test
      run: test/basic/basic
